"""
OTP Authentication Tests
========================

Tests the phone-number OTP flow with a mocked SMS service.
All OTPs are intercepted via monkeypatch — no real SMS is sent.
"""

import random
import pytest
from unittest.mock import patch, MagicMock


def generate_unique_phone() -> str:
    """Generate a valid unique E.164 phone number for isolated test runs."""
    return f"+9198{random.randint(10000000, 99999999)}"


# ── Helper: intercept OTP before it's hashed ─────────────────────────────────

class OTPCapture:
    """Captures the plaintext OTP generated by otp_service for test verification."""
    last_otp: str = ""

    @staticmethod
    def mock_create_otp_record(db, phone):
        from app.services import otp_service
        otp = otp_service.generate_otp()
        OTPCapture.last_otp = otp
        # Store the hash normally
        from app.models.otp_verification import OTPVerification
        from datetime import datetime, timedelta, timezone
        from app.core.config import settings

        now = datetime.now(timezone.utc)

        # Invalidate old unverified OTPs
        db.query(OTPVerification).filter(
            OTPVerification.phone_number == phone,
            OTPVerification.is_verified == False,  # noqa: E712
        ).update({"is_verified": True})

        record = OTPVerification(
            phone_number=phone,
            otp_hash=otp_service.hash_otp(otp),
            expires_at=now + timedelta(seconds=settings.OTP_EXPIRY_SECONDS),
            attempt_count=0,
            max_attempts=settings.OTP_MAX_ATTEMPTS,
            is_verified=False,
        )
        db.add(record)
        db.commit()
        return otp


# ── Patch target for SMS service (patch where it's USED, not where defined) ──
SMS_PATCH_TARGET = "app.services.auth_service.get_sms_service"
OTP_PATCH_TARGET = "app.services.auth_service.otp_service.create_otp_record"


@pytest.fixture(autouse=True)
def _reset_rate_limiter():
    """Reset the rate limiter between tests to prevent cross-test interference."""
    from app.core.rate_limit import limiter
    limiter.reset()
    yield
    limiter.reset()


# ── Send OTP Tests ───────────────────────────────────────────────────────────

@patch(SMS_PATCH_TARGET)
def test_send_otp_valid_phone(mock_sms, client):
    """Valid phone number should return 200 and 'OTP sent successfully'."""
    mock_service = MagicMock()
    mock_service.send_otp.return_value = True
    mock_sms.return_value = mock_service

    phone = generate_unique_phone()
    res = client.post("/api/auth/send-otp", json={"phone": phone})
    assert res.status_code == 200
    assert res.json()["message"] == "OTP sent successfully."
    mock_service.send_otp.assert_called_once()


def test_send_otp_invalid_phone(client):
    """Invalid phone number should return 400."""
    res = client.post("/api/auth/send-otp", json={"phone": "not-a-phone"})
    assert res.status_code == 400


def test_send_otp_empty_phone(client):
    """Empty phone number should return 422 (validation error)."""
    res = client.post("/api/auth/send-otp", json={"phone": ""})
    assert res.status_code == 422


# ── Verify OTP Tests ─────────────────────────────────────────────────────────

@patch(SMS_PATCH_TARGET)
@patch(OTP_PATCH_TARGET, side_effect=OTPCapture.mock_create_otp_record)
def test_verify_otp_correct(mock_create, mock_sms, client):
    """Correct OTP should return 200, JWT, and user data."""
    mock_service = MagicMock()
    mock_service.send_otp.return_value = True
    mock_sms.return_value = mock_service

    phone = generate_unique_phone()

    # Step 1: Send OTP
    send_res = client.post("/api/auth/send-otp", json={"phone": phone})
    assert send_res.status_code == 200

    # Step 2: Verify with captured OTP
    otp = OTPCapture.last_otp
    verify_res = client.post("/api/auth/verify-otp", json={
        "phone": phone,
        "otp": otp,
    })
    assert verify_res.status_code == 200
    data = verify_res.json()
    assert data["message"] == "Login successful."
    assert "access_token" in data
    assert data["token_type"] == "bearer"
    assert data["user"]["role"]["name"] == "Candidate"
    assert data["is_new_user"] is True


@patch(SMS_PATCH_TARGET)
@patch(OTP_PATCH_TARGET, side_effect=OTPCapture.mock_create_otp_record)
def test_verify_otp_incorrect(mock_create, mock_sms, client):
    """Incorrect OTP should return 401."""
    mock_service = MagicMock()
    mock_service.send_otp.return_value = True
    mock_sms.return_value = mock_service

    phone = generate_unique_phone()
    client.post("/api/auth/send-otp", json={"phone": phone})

    verify_res = client.post("/api/auth/verify-otp", json={
        "phone": phone,
        "otp": "000000",
    })
    assert verify_res.status_code == 401
    assert "Invalid OTP" in verify_res.json()["detail"]


def test_verify_otp_no_otp_requested(client):
    """Verify without sending OTP first should return 401."""
    phone = generate_unique_phone()
    res = client.post("/api/auth/verify-otp", json={
        "phone": phone,
        "otp": "123456",
    })
    assert res.status_code == 401
    assert "No OTP found" in res.json()["detail"]


def test_verify_otp_invalid_format(client):
    """OTP that is not 6 digits should return 422."""
    phone = generate_unique_phone()
    res = client.post("/api/auth/verify-otp", json={
        "phone": phone,
        "otp": "12345",  # only 5 digits
    })
    assert res.status_code == 422


# ── OTP One-Time Use Test ────────────────────────────────────────────────────

@patch(SMS_PATCH_TARGET)
@patch(OTP_PATCH_TARGET, side_effect=OTPCapture.mock_create_otp_record)
def test_otp_one_time_use(mock_create, mock_sms, client):
    """Using the same OTP twice should fail the second time."""
    mock_service = MagicMock()
    mock_service.send_otp.return_value = True
    mock_sms.return_value = mock_service

    phone = generate_unique_phone()
    client.post("/api/auth/send-otp", json={"phone": phone})
    otp = OTPCapture.last_otp

    # First verify — should succeed
    res1 = client.post("/api/auth/verify-otp", json={"phone": phone, "otp": otp})
    assert res1.status_code == 200

    # Second verify with same OTP — should fail
    res2 = client.post("/api/auth/verify-otp", json={"phone": phone, "otp": otp})
    assert res2.status_code == 401


# ── Existing User Does Not Create Duplicate ──────────────────────────────────

@patch(SMS_PATCH_TARGET)
@patch(OTP_PATCH_TARGET, side_effect=OTPCapture.mock_create_otp_record)
def test_existing_user_no_duplicate(mock_create, mock_sms, client):
    """If a user already exists for this phone, OTP login should not create a new one."""
    mock_service = MagicMock()
    mock_service.send_otp.return_value = True
    mock_sms.return_value = mock_service

    phone = generate_unique_phone()

    # First login — creates user
    client.post("/api/auth/send-otp", json={"phone": phone})
    otp1 = OTPCapture.last_otp
    res1 = client.post("/api/auth/verify-otp", json={"phone": phone, "otp": otp1})
    assert res1.status_code == 200
    user_id_1 = res1.json()["user"]["id"]
    assert res1.json()["is_new_user"] is True

    # Second login — same user
    client.post("/api/auth/send-otp", json={"phone": phone})
    otp2 = OTPCapture.last_otp
    res2 = client.post("/api/auth/verify-otp", json={"phone": phone, "otp": otp2})
    assert res2.status_code == 200
    user_id_2 = res2.json()["user"]["id"]
    assert res2.json()["is_new_user"] is False
    assert user_id_1 == user_id_2


# ── JWT from OTP Login Works ─────────────────────────────────────────────────

@patch(SMS_PATCH_TARGET)
@patch(OTP_PATCH_TARGET, side_effect=OTPCapture.mock_create_otp_record)
def test_otp_jwt_works_on_protected_endpoint(mock_create, mock_sms, client):
    """JWT obtained from OTP login should work on /api/auth/me."""
    mock_service = MagicMock()
    mock_service.send_otp.return_value = True
    mock_sms.return_value = mock_service

    phone = generate_unique_phone()
    client.post("/api/auth/send-otp", json={"phone": phone})
    otp = OTPCapture.last_otp

    verify_res = client.post("/api/auth/verify-otp", json={"phone": phone, "otp": otp})
    assert verify_res.status_code == 200
    token = verify_res.json()["access_token"]

    me_res = client.get("/api/auth/me", headers={"Authorization": f"Bearer {token}"})
    assert me_res.status_code == 200
    assert me_res.json()["phone_number"] == phone
    assert me_res.json()["role"]["name"] == "Candidate"


# ── Existing Email+Password Login Still Works ────────────────────────────────

def test_existing_email_login_still_works(client):
    """Existing email+password login should still work after OTP changes."""
    res = client.post("/api/auth/login", json={
        "email": "admin@skillaign.dev",
        "password": "Admin@123"
    })
    assert res.status_code == 200
    assert "access_token" in res.json()
