"""add_multi_recruiter_assignments_communication_tasks_audit

Revision ID: e5343d43c41b
Revises: 917c18d1a593
Create Date: 2026-09-06 08:32:26.397935+00:00
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5343d43c41b'
down_revision: Union[str, None] = '917c18d1a593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_candidate_id'), 'audit_logs', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_job_id'), 'audit_logs', ['job_id'], unique=False)
    op.create_table('candidate_recruiter_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_job_candidate_assignment')
    )
    op.create_index(op.f('ix_candidate_recruiter_assignments_candidate_id'), 'candidate_recruiter_assignments', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_recruiter_assignments_job_id'), 'candidate_recruiter_assignments', ['job_id'], unique=False)
    op.create_index(op.f('ix_candidate_recruiter_assignments_recruiter_id'), 'candidate_recruiter_assignments', ['recruiter_id'], unique=False)
    op.create_index(op.f('ix_candidate_recruiter_assignments_status'), 'candidate_recruiter_assignments', ['status'], unique=False)
    op.create_table('job_recruiter_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assignment_role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'recruiter_id', name='uq_job_recruiter')
    )
    op.create_index(op.f('ix_job_recruiter_assignments_job_id'), 'job_recruiter_assignments', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_recruiter_assignments_recruiter_id'), 'job_recruiter_assignments', ['recruiter_id'], unique=False)
    op.create_index(op.f('ix_job_recruiter_assignments_status'), 'job_recruiter_assignments', ['status'], unique=False)
    op.create_table('recruitment_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruitment_messages_candidate_id'), 'recruitment_messages', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_recruitment_messages_job_id'), 'recruitment_messages', ['job_id'], unique=False)
    op.create_index(op.f('ix_recruitment_messages_sender_id'), 'recruitment_messages', ['sender_id'], unique=False)
    op.create_table('recruitment_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruitment_tasks_assigned_to'), 'recruitment_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_recruitment_tasks_candidate_id'), 'recruitment_tasks', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_recruitment_tasks_created_by'), 'recruitment_tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_recruitment_tasks_job_id'), 'recruitment_tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_recruitment_tasks_status'), 'recruitment_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_tasks_status'), table_name='recruitment_tasks')
    op.drop_index(op.f('ix_recruitment_tasks_job_id'), table_name='recruitment_tasks')
    op.drop_index(op.f('ix_recruitment_tasks_created_by'), table_name='recruitment_tasks')
    op.drop_index(op.f('ix_recruitment_tasks_candidate_id'), table_name='recruitment_tasks')
    op.drop_index(op.f('ix_recruitment_tasks_assigned_to'), table_name='recruitment_tasks')
    op.drop_table('recruitment_tasks')
    op.drop_index(op.f('ix_recruitment_messages_sender_id'), table_name='recruitment_messages')
    op.drop_index(op.f('ix_recruitment_messages_job_id'), table_name='recruitment_messages')
    op.drop_index(op.f('ix_recruitment_messages_candidate_id'), table_name='recruitment_messages')
    op.drop_table('recruitment_messages')
    op.drop_index(op.f('ix_job_recruiter_assignments_status'), table_name='job_recruiter_assignments')
    op.drop_index(op.f('ix_job_recruiter_assignments_recruiter_id'), table_name='job_recruiter_assignments')
    op.drop_index(op.f('ix_job_recruiter_assignments_job_id'), table_name='job_recruiter_assignments')
    op.drop_table('job_recruiter_assignments')
    op.drop_index(op.f('ix_candidate_recruiter_assignments_status'), table_name='candidate_recruiter_assignments')
    op.drop_index(op.f('ix_candidate_recruiter_assignments_recruiter_id'), table_name='candidate_recruiter_assignments')
    op.drop_index(op.f('ix_candidate_recruiter_assignments_job_id'), table_name='candidate_recruiter_assignments')
    op.drop_index(op.f('ix_candidate_recruiter_assignments_candidate_id'), table_name='candidate_recruiter_assignments')
    op.drop_table('candidate_recruiter_assignments')
    op.drop_index(op.f('ix_audit_logs_job_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_candidate_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
