"""add_multiround_and_offer_approval_workflow

Revision ID: c6db23ef1513
Revises: 789b7e27973f
Create Date: 2026-09-08 18:28:40.283085+00:00
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6db23ef1513'
down_revision: Union[str, None] = '789b7e27973f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_interview_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('round_name', sa.String(length=100), nullable=False),
    sa.Column('round_type', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_interview_rounds_job_id'), 'job_interview_rounds', ['job_id'], unique=False)

    # Add NOT NULL columns with server_default to handle existing rows
    op.add_column('interviews', sa.Column('round_number', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('interviews', sa.Column('round_name', sa.String(length=100), nullable=True))
    op.add_column('interviews', sa.Column('round_type', sa.String(length=50), server_default=sa.text("'TECHNICAL'"), nullable=False))
    op.add_column('interviews', sa.Column('round_status', sa.String(length=30), server_default=sa.text("'PENDING_SCHEDULING'"), nullable=False))
    op.add_column('interviews', sa.Column('is_additional_round', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('interviews', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('candidate_slot_id', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('hm_recommendation', sa.String(length=20), nullable=True))
    op.add_column('interviews', sa.Column('hm_technical_rating', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('hm_communication_rating', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('hm_problem_solving_rating', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('hm_role_fit_rating', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('hm_overall_rating', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('hm_comments', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('hm_feedback_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_interviews_interviewer_id'), 'interviews', ['interviewer_id'], unique=False)
    op.create_index(op.f('ix_interviews_round_number'), 'interviews', ['round_number'], unique=False)
    op.create_index(op.f('ix_interviews_round_status'), 'interviews', ['round_status'], unique=False)
    op.create_foreign_key(None, 'interviews', 'interview_slots', ['candidate_slot_id'], ['id'], ondelete='SET NULL')

    # Add NOT NULL offer columns with server_default
    op.add_column('offers', sa.Column('workflow_state', sa.String(length=50), server_default=sa.text("'DRAFT'"), nullable=False))
    op.add_column('offers', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('offers', sa.Column('hm_comments', sa.Text(), nullable=True))
    op.add_column('offers', sa.Column('recruiter_comments', sa.Text(), nullable=True))
    op.add_column('offers', sa.Column('pdf_storage_key', sa.String(length=500), nullable=True))
    op.add_column('offers', sa.Column('pdf_file_name', sa.String(length=255), nullable=True))
    op.add_column('offers', sa.Column('pdf_file_size', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('pdf_mime_type', sa.String(length=100), nullable=True))
    op.add_column('offers', sa.Column('pdf_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('offers', sa.Column('pdf_generated_by', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('secure_access_token_hash', sa.String(length=128), nullable=True))
    op.add_column('offers', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('offers', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('offers', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_index(op.f('ix_offers_workflow_state'), 'offers', ['workflow_state'], unique=False)
    op.create_foreign_key(None, 'offers', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'offers', 'users', ['pdf_generated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_index(op.f('ix_offers_workflow_state'), table_name='offers')
    op.alter_column('offers', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('offers', 'expires_at')
    op.drop_column('offers', 'token_expires_at')
    op.drop_column('offers', 'secure_access_token_hash')
    op.drop_column('offers', 'pdf_generated_by')
    op.drop_column('offers', 'pdf_generated_at')
    op.drop_column('offers', 'pdf_mime_type')
    op.drop_column('offers', 'pdf_file_size')
    op.drop_column('offers', 'pdf_file_name')
    op.drop_column('offers', 'pdf_storage_key')
    op.drop_column('offers', 'recruiter_comments')
    op.drop_column('offers', 'hm_comments')
    op.drop_column('offers', 'approved_at')
    op.drop_column('offers', 'approved_by')
    op.drop_column('offers', 'workflow_state')
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_index(op.f('ix_interviews_round_status'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_round_number'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_interviewer_id'), table_name='interviews')
    op.drop_column('interviews', 'hm_feedback_submitted_at')
    op.drop_column('interviews', 'hm_comments')
    op.drop_column('interviews', 'hm_overall_rating')
    op.drop_column('interviews', 'hm_role_fit_rating')
    op.drop_column('interviews', 'hm_problem_solving_rating')
    op.drop_column('interviews', 'hm_communication_rating')
    op.drop_column('interviews', 'hm_technical_rating')
    op.drop_column('interviews', 'hm_recommendation')
    op.drop_column('interviews', 'candidate_slot_id')
    op.drop_column('interviews', 'duration_minutes')
    op.drop_column('interviews', 'is_additional_round')
    op.drop_column('interviews', 'round_status')
    op.drop_column('interviews', 'round_type')
    op.drop_column('interviews', 'round_name')
    op.drop_column('interviews', 'round_number')
    op.drop_index(op.f('ix_job_interview_rounds_job_id'), table_name='job_interview_rounds')
    op.drop_table('job_interview_rounds')
    # ### end Alembic commands ###
