"""add_enterprise_workflow_models

Revision ID: 789b7e27973f
Revises: e5343d43c41b
Create Date: 2026-09-08 10:04:31.964076+00:00
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '789b7e27973f'
down_revision: Union[str, None] = 'e5343d43c41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_blacklists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('match_result_id', sa.Integer(), nullable=True),
    sa.Column('blacklisted_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('blacklisted_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['blacklisted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_blacklists_blacklisted_by'), 'candidate_blacklists', ['blacklisted_by'], unique=False)
    op.create_index(op.f('ix_candidate_blacklists_candidate_id'), 'candidate_blacklists', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_blacklists_is_active'), 'candidate_blacklists', ['is_active'], unique=False)
    op.create_index(op.f('ix_candidate_blacklists_match_result_id'), 'candidate_blacklists', ['match_result_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_result_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('proposed_salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('joining_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offer_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('work_mode', sa.String(length=50), nullable=True),
    sa.Column('additional_terms', sa.Text(), nullable=True),
    sa.Column('offer_token', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('candidate_response_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_candidate_id'), 'offers', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_offers_created_by'), 'offers', ['created_by'], unique=False)
    op.create_index(op.f('ix_offers_job_id'), 'offers', ['job_id'], unique=False)
    op.create_index(op.f('ix_offers_match_result_id'), 'offers', ['match_result_id'], unique=True)
    op.create_index(op.f('ix_offers_offer_token'), 'offers', ['offer_token'], unique=True)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_table('interview_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('match_result_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('go_no_go', sa.String(length=10), nullable=False),
    sa.Column('technical_rating', sa.Integer(), nullable=True),
    sa.Column('communication_rating', sa.Integer(), nullable=True),
    sa.Column('problem_solving_rating', sa.Integer(), nullable=True),
    sa.Column('role_fit_rating', sa.Integer(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("go_no_go IN ('GO', 'NO_GO')", name='ck_feedback_go_no_go'),
    sa.CheckConstraint('communication_rating BETWEEN 1 AND 5', name='ck_feedback_communication_rating'),
    sa.CheckConstraint('overall_rating BETWEEN 1 AND 5', name='ck_feedback_overall_rating'),
    sa.CheckConstraint('problem_solving_rating BETWEEN 1 AND 5', name='ck_feedback_problem_solving_rating'),
    sa.CheckConstraint('role_fit_rating BETWEEN 1 AND 5', name='ck_feedback_role_fit_rating'),
    sa.CheckConstraint('technical_rating BETWEEN 1 AND 5', name='ck_feedback_technical_rating'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_feedback_interview_id'), 'interview_feedback', ['interview_id'], unique=True)
    op.create_index(op.f('ix_interview_feedback_match_result_id'), 'interview_feedback', ['match_result_id'], unique=False)
    op.create_index(op.f('ix_interview_feedback_reviewer_id'), 'interview_feedback', ['reviewer_id'], unique=False)
    op.create_table('interview_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('match_result_id', sa.Integer(), nullable=False),
    sa.Column('proposed_by', sa.Integer(), nullable=True),
    sa.Column('slot_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot_end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_slots_interview_id'), 'interview_slots', ['interview_id'], unique=False)
    op.create_index(op.f('ix_interview_slots_match_result_id'), 'interview_slots', ['match_result_id'], unique=False)
    op.create_index(op.f('ix_interview_slots_proposed_by'), 'interview_slots', ['proposed_by'], unique=False)
    op.create_index(op.f('ix_interview_slots_status'), 'interview_slots', ['status'], unique=False)
    op.add_column('audit_logs', sa.Column('match_result_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('interview_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('from_state', sa.String(length=60), nullable=True))
    op.add_column('audit_logs', sa.Column('to_state', sa.String(length=60), nullable=True))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.create_index(op.f('ix_audit_logs_interview_id'), 'audit_logs', ['interview_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_match_result_id'), 'audit_logs', ['match_result_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'match_results', ['match_result_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'audit_logs', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.add_column('interviews', sa.Column('requested_by', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('confirmed_by', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('slot_token', sa.String(length=64), nullable=True))
    op.add_column('interviews', sa.Column('candidate_selection_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interviews', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('interviews', 'interview_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_interviews_confirmed_by'), 'interviews', ['confirmed_by'], unique=False)
    op.create_index(op.f('ix_interviews_requested_by'), 'interviews', ['requested_by'], unique=False)
    op.create_index(op.f('ix_interviews_slot_token'), 'interviews', ['slot_token'], unique=True)
    op.create_foreign_key(None, 'interviews', 'users', ['confirmed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'interviews', 'users', ['requested_by'], ['id'], ondelete='SET NULL')
    op.add_column('match_results', sa.Column('pipeline_state', sa.String(length=60), nullable=True, server_default='CANDIDATE_MATCHED'))
    op.execute("UPDATE match_results SET pipeline_state = 'CANDIDATE_MATCHED' WHERE pipeline_state IS NULL")
    op.alter_column('match_results', 'pipeline_state', nullable=False, server_default=None)
    op.add_column('match_results', sa.Column('hiring_manager_id', sa.Integer(), nullable=True))
    op.add_column('match_results', sa.Column('shortlist_note', sa.Text(), nullable=True))
    op.add_column('match_results', sa.Column('submitted_to_hm_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('match_results', sa.Column('hm_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('match_results', sa.Column('hm_rejection_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_match_results_hiring_manager_id'), 'match_results', ['hiring_manager_id'], unique=False)
    op.create_index(op.f('ix_match_results_pipeline_state'), 'match_results', ['pipeline_state'], unique=False)
    op.create_foreign_key(None, 'match_results', 'users', ['hiring_manager_id'], ['id'], ondelete='SET NULL')
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=True, server_default='false'))
    op.execute("UPDATE notifications SET is_read = false WHERE is_read IS NULL")
    op.alter_column('notifications', 'is_read', nullable=False, server_default=None)
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=60), nullable=True))
    op.add_column('notifications', sa.Column('match_result_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('action_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_match_result_id'), 'notifications', ['match_result_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_foreign_key(None, 'notifications', 'match_results', ['match_result_id'], ['id'], ondelete='CASCADE')
    op.add_column('recruitment_tasks', sa.Column('match_result_id', sa.Integer(), nullable=True))
    op.add_column('recruitment_tasks', sa.Column('interview_id', sa.Integer(), nullable=True))
    op.add_column('recruitment_tasks', sa.Column('action_type', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_recruitment_tasks_action_type'), 'recruitment_tasks', ['action_type'], unique=False)
    op.create_index(op.f('ix_recruitment_tasks_interview_id'), 'recruitment_tasks', ['interview_id'], unique=False)
    op.create_index(op.f('ix_recruitment_tasks_match_result_id'), 'recruitment_tasks', ['match_result_id'], unique=False)
    op.create_foreign_key(None, 'recruitment_tasks', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recruitment_tasks', 'match_results', ['match_result_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruitment_tasks', type_='foreignkey')
    op.drop_constraint(None, 'recruitment_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_recruitment_tasks_match_result_id'), table_name='recruitment_tasks')
    op.drop_index(op.f('ix_recruitment_tasks_interview_id'), table_name='recruitment_tasks')
    op.drop_index(op.f('ix_recruitment_tasks_action_type'), table_name='recruitment_tasks')
    op.drop_column('recruitment_tasks', 'action_type')
    op.drop_column('recruitment_tasks', 'interview_id')
    op.drop_column('recruitment_tasks', 'match_result_id')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_match_result_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'match_result_id')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'is_read')
    op.drop_constraint(None, 'match_results', type_='foreignkey')
    op.drop_index(op.f('ix_match_results_pipeline_state'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_hiring_manager_id'), table_name='match_results')
    op.drop_column('match_results', 'hm_rejection_reason')
    op.drop_column('match_results', 'hm_reviewed_at')
    op.drop_column('match_results', 'submitted_to_hm_at')
    op.drop_column('match_results', 'shortlist_note')
    op.drop_column('match_results', 'hiring_manager_id')
    op.drop_column('match_results', 'pipeline_state')
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_index(op.f('ix_interviews_slot_token'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_requested_by'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_confirmed_by'), table_name='interviews')
    op.alter_column('interviews', 'interview_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('interviews', 'confirmed_at')
    op.drop_column('interviews', 'candidate_selection_at')
    op.drop_column('interviews', 'slot_token')
    op.drop_column('interviews', 'confirmed_by')
    op.drop_column('interviews', 'requested_by')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_match_result_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_interview_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('audit_logs', 'to_state')
    op.drop_column('audit_logs', 'from_state')
    op.drop_column('audit_logs', 'interview_id')
    op.drop_column('audit_logs', 'match_result_id')
    op.drop_index(op.f('ix_interview_slots_status'), table_name='interview_slots')
    op.drop_index(op.f('ix_interview_slots_proposed_by'), table_name='interview_slots')
    op.drop_index(op.f('ix_interview_slots_match_result_id'), table_name='interview_slots')
    op.drop_index(op.f('ix_interview_slots_interview_id'), table_name='interview_slots')
    op.drop_table('interview_slots')
    op.drop_index(op.f('ix_interview_feedback_reviewer_id'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_match_result_id'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_interview_id'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_offer_token'), table_name='offers')
    op.drop_index(op.f('ix_offers_match_result_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_job_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_created_by'), table_name='offers')
    op.drop_index(op.f('ix_offers_candidate_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_candidate_blacklists_match_result_id'), table_name='candidate_blacklists')
    op.drop_index(op.f('ix_candidate_blacklists_is_active'), table_name='candidate_blacklists')
    op.drop_index(op.f('ix_candidate_blacklists_candidate_id'), table_name='candidate_blacklists')
    op.drop_index(op.f('ix_candidate_blacklists_blacklisted_by'), table_name='candidate_blacklists')
    op.drop_table('candidate_blacklists')
    # ### end Alembic commands ###
