"""add_skill_source_evidence_and_match_processing_status

Revision ID: 917c18d1a593
Revises: b69986853266
Create Date: 2026-09-05 19:39:22.483824+00:00
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917c18d1a593'
down_revision: Union[str, None] = 'b69986853266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── candidate_skills: add source column with default to backfill existing rows ──
    op.add_column('candidate_skills', sa.Column(
        'source', sa.String(length=20),
        server_default='manual',  # Backfill existing skills as 'manual' (self-declared)
        nullable=False,
    ))
    op.add_column('candidate_skills', sa.Column('evidence_text', sa.Text(), nullable=True))
    op.add_column('candidate_skills', sa.Column(
        'created_at', sa.DateTime(timezone=True),
        server_default=sa.text('now()'), nullable=False,
    ))
    op.add_column('candidate_skills', sa.Column(
        'updated_at', sa.DateTime(timezone=True),
        server_default=sa.text('now()'), nullable=False,
    ))
    # Make proficiency_level nullable (None = resume-detected, unknown proficiency)
    op.alter_column(
        'candidate_skills', 'proficiency_level',
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'Beginner'::character varying"),
    )
    # Remove the hard-coded default after backfill — app controls this value
    op.alter_column('candidate_skills', 'source', server_default=None)
    op.create_index(op.f('ix_candidate_skills_source'), 'candidate_skills', ['source'], unique=False)

    # ── match_results: add processing_status with default for existing rows ────────
    op.add_column('match_results', sa.Column(
        'processing_status', sa.String(length=20),
        server_default='completed',  # Existing match results are considered complete
        nullable=False,
    ))
    # Remove the hard-coded default after backfill
    op.alter_column('match_results', 'processing_status', server_default=None)
    op.add_column('match_results', sa.Column('matched_by_version', sa.Integer(), nullable=True))
    op.alter_column(
        'match_results', 'status',
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'screening'::character varying"),
    )
    op.create_index(op.f('ix_match_results_processing_status'), 'match_results', ['processing_status'], unique=False)
    op.create_index(op.f('ix_match_results_recruiter_id'), 'match_results', ['recruiter_id'], unique=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_results_recruiter_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_processing_status'), table_name='match_results')
    op.alter_column('match_results', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'screening'::character varying"))
    op.drop_column('match_results', 'matched_by_version')
    op.drop_column('match_results', 'processing_status')
    op.drop_index(op.f('ix_candidate_skills_source'), table_name='candidate_skills')
    op.alter_column('candidate_skills', 'proficiency_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Beginner'::character varying"))
    op.drop_column('candidate_skills', 'updated_at')
    op.drop_column('candidate_skills', 'created_at')
    op.drop_column('candidate_skills', 'evidence_text')
    op.drop_column('candidate_skills', 'source')
    # ### end Alembic commands ###
